theme = "catppuccin_mocha"

[editor]
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
A-f = ":format" # format
A-s = ":w" # save file
A-w = ":wq" # save and quit
A-q = ":quit" # quit
A-Q = ":quit-all!" # force quit all
A-v = "paste_before" # paste yank
A-c = "yank" # yank (copy)
C-left = "move_prev_word_start" # move previous word
C-right = "move_next_word_start" # move next word

[keys.insert]
A-f = ":format" # format
A-s = ":w" # save file
A-w = ":wq" # save and quit
A-q = ":quit" # quit
A-Q = ":quit-all!" # force quit all
A-v = "paste_before" #paste yank
C-left = "move_prev_word_start" # move previous word
C-right = "move_next_word_start" # move next word

[keys.select]
A-c = "yank" # yank (copy)
